name: Build Unsigned APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install dependencies and prebuild Expo
        run: |
          yarn install
          yarn bundle:es
          yarn expo prebuild -p android --clean --no-install

      - name: Build unsigned release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Show output APK path
        run: ls -lh android/app/build/outputs/apk/release/

      - name: Upload unsigned APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: android/app/build/outputs/apk/release/*.apk
